#!/usr/bin/env python3
"""
Assemble the static site that gets deployed to Cloudflare.

Collects the generated .ics feeds into public/ alongside the _headers and
_redirects files Cloudflare needs, then validates every feed before it can be
published. Deploying a broken or empty calendar is worse than not deploying, so
this exits non-zero rather than shipping one.

Usage:
    python build_site.py            # writes ./public
"""

import shutil
import sys
from pathlib import Path
from urllib.parse import quote

from icalendar import Calendar

PUBLIC_DIR = Path("public")
CURRENT_FEED = "woodstockfilmfestival.ics"
ARCHIVE_GLOB = "wff_*_complete.ics"

SITE_URL = "https://woodstock-filmfestival-calendar-generator.themorgantown.workers.dev"

# An https:// link to a .ics makes the browser download a one-off snapshot.
# webcal:// hands the URL to the calendar app, which subscribes and keeps polling.
WEBCAL_URL = SITE_URL.replace("https://", "webcal://")
CALENDAR_NAME = "Woodstock Film Festival"

# Screenshot of Apple Calendar's subscribe menu, shown alongside the manual steps
SCREENSHOT = "calendar_add.png"

# The live feed changes hourly; frozen archives can be cached hard.
CURRENT_CACHE = "public, max-age=1800"
ARCHIVE_CACHE = "public, max-age=86400"


def validate(path: Path) -> int:
    """Parse a feed and return its event count. Raises if it isn't a usable calendar"""
    cal = Calendar.from_ical(path.read_text(encoding="utf-8"))
    return len(list(cal.walk("VEVENT")))


def build_headers(feeds: dict[str, str]) -> str:
    """One explicit block per feed - no reliance on extension globbing"""
    lines = [
        "# Generated by build_site.py - do not edit by hand",
        "",
    ]
    for name, cache in feeds.items():
        lines += [
            f"/{name}",
            "  Content-Type: text/calendar; charset=utf-8",
            f"  Cache-Control: {cache}",
            "  Access-Control-Allow-Origin: *",
            "",
        ]
    return "\n".join(lines)


REDIRECTS = f"""# Generated by build_site.py - do not edit by hand

# Short aliases for the one feed we advertise
/calendar.ics  /{CURRENT_FEED}  301
/subscribe     /{CURRENT_FEED}  301

# When a festival year goes stale you can point its path at the current feed
# instead of leaving subscribers on dead data, e.g:
# /wff_2025_complete.ics  /{CURRENT_FEED}  301
# Left commented out on purpose: the year files are kept as a working archive.
"""


def build_index(current_events: int, archives: list[tuple[str, int]]) -> str:
    archive_rows = "\n".join(
        f'      <li><a href="/{name}">{name}</a> <span>{count} events</span></li>'
        for name, count in archives
    )

    feed_https = f"{SITE_URL}/{CURRENT_FEED}"
    feed_webcal = f"{WEBCAL_URL}/{CURRENT_FEED}"
    google_url = ("https://calendar.google.com/calendar/r?cid="
                  + quote(feed_webcal, safe=""))
    outlook_url = ("https://outlook.live.com/calendar/0/addfromweb?url="
                   + quote(feed_https, safe="")
                   + "&name=" + quote(CALENDAR_NAME, safe=""))
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Woodstock Film Festival Calendar (Unofficial)</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{ margin: 0 auto; padding: 2.5rem 1.25rem; max-width: 42rem;
         font: 16px/1.6 system-ui, -apple-system, sans-serif; }}
  h1 {{ font-size: 1.6rem; margin-bottom: .25rem; }}
  p.sub {{ margin-top: 0; opacity: .7; }}
  code {{ background: rgba(128,128,128,.15); padding: .15em .4em; border-radius: 4px;
          word-break: break-all; }}
  .cta {{ display: inline-block; margin: 1rem 0; padding: .7rem 1.2rem; border-radius: 8px;
          background: #1f6feb; color: #fff; text-decoration: none; font-weight: 600; }}
  .alt {{ display: flex; flex-wrap: wrap; gap: .5rem; margin: .5rem 0 1.25rem; }}
  .alt a {{ padding: .5rem .9rem; border-radius: 8px; text-decoration: none;
            border: 1px solid rgba(128,128,128,.45); color: inherit; font-size: .95rem; }}
  .note {{ font-size: .9rem; opacity: .7; }}
  figure {{ margin: 1rem 0; }}
  figure img {{ max-width: 100%; height: auto; border-radius: 10px;
                border: 1px solid rgba(128,128,128,.35); }}
  figcaption {{ font-size: .85rem; opacity: .7; margin-top: .4rem; }}
  ul {{ padding-left: 1.2rem; }}
  li span {{ opacity: .6; font-size: .9em; }}
  footer {{ margin-top: 2.5rem; font-size: .9em; opacity: .7; }}
</style>
</head>
<body>
  <h1>Woodstock Film Festival Calendar</h1>
  <p class="sub">Unofficial, auto-generated, updated hourly. Currently {current_events} events.</p>

  <a class="cta" href="{feed_webcal}">Subscribe in your calendar app</a>

  <div class="alt">
    <a href="{google_url}" target="_blank" rel="noopener">Add to Google Calendar</a>
    <a href="{outlook_url}" target="_blank" rel="noopener">Add to Outlook</a>
    <a href="/{CURRENT_FEED}" download>Download .ics</a>
  </div>

  <p class="note">
    Subscribing keeps the calendar up to date automatically. Downloading the .ics
    imports a one-time snapshot that never changes - use it only if subscribing fails.
  </p>

  <p>Or paste this URL into your calendar app:</p>
  <p style="font-family: monospace;font-size:larger"><code>{SITE_URL}/{CURRENT_FEED}</code></p>
  <p>This URL always points at the current festival, so you only subscribe once.</p>

  <figure>
    <img src="/{SCREENSHOT}" alt="The macOS Calendar File menu with New Calendar Subscription highlighted"
         width="672" height="636" loading="lazy">
    <figcaption>In Apple Calendar: File &rarr; New Calendar Subscription&hellip;, then paste the URL above.</figcaption>
  </figure>

  <h2>Archive</h2>
  <p>Past festivals, kept as-is and no longer updated:</p>
  <ul>
{archive_rows}
  </ul>

  <footer>
    Unofficial - please verify details on the
    <a href="https://woodstockfilmfestival.org">official festival site</a>.
    <a href="https://github.com/themorgantown/woodstock-filmfestival-calendar-generator">Source</a>.
  </footer>
</body>
</html>
"""


def main():
    current = Path(CURRENT_FEED)
    if not current.exists():
        sys.exit(f"✗ {CURRENT_FEED} is missing - run make_calendar.py first")

    current_events = validate(current)
    if current_events == 0:
        sys.exit(f"✗ {CURRENT_FEED} has no events - refusing to deploy an empty calendar")

    archives = sorted(p for p in Path(".").glob(ARCHIVE_GLOB))

    if PUBLIC_DIR.exists():
        shutil.rmtree(PUBLIC_DIR)
    PUBLIC_DIR.mkdir()

    feeds = {CURRENT_FEED: CURRENT_CACHE}
    archive_info = []

    shutil.copy2(current, PUBLIC_DIR / CURRENT_FEED)
    for path in archives:
        count = validate(path)
        shutil.copy2(path, PUBLIC_DIR / path.name)
        feeds[path.name] = ARCHIVE_CACHE
        archive_info.append((path.name, count))

    screenshot = Path(SCREENSHOT)
    if screenshot.exists():
        shutil.copy2(screenshot, PUBLIC_DIR / SCREENSHOT)
    else:
        print(f"  ! {SCREENSHOT} not found - page will render without it")

    (PUBLIC_DIR / "_headers").write_text(build_headers(feeds), encoding="utf-8")
    (PUBLIC_DIR / "_redirects").write_text(REDIRECTS, encoding="utf-8")
    (PUBLIC_DIR / "index.html").write_text(
        build_index(current_events, archive_info), encoding="utf-8"
    )

    print(f"✓ Built {PUBLIC_DIR}/")
    print(f"  {CURRENT_FEED}: {current_events} events")
    for name, count in archive_info:
        print(f"  {name}: {count} events (archive)")


if __name__ == "__main__":
    main()
